name: Pull request checks

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  black-format-check: # Check that the codebase is formatted with black
    name: Black format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
      - name: Install dependencies and check black format
        run: |
          cd tadkit
          python -m pip install --upgrade pip
          pip install black
          black --check --diff .

  flake8-check: # Check that the codebase does not contain linting errors
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
      - name: Install dependencies and check flake8 format
        run: |
          cd tadkit
          python -m pip install --upgrade pip
          pip install flake8
          flake8 .

  python-tests: # Install dependencies and run tests with pytest
    name: Python tests
    needs:
      [black-format-check, prettier-check, cspell-check, version-upgrade-check]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest tests/

  docker-build-check: # Build the docker image and check that it can run
    name: Docker build check
    needs:
      [black-format-check, prettier-check, cspell-check, version-upgrade-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        run: |
          docker build -t tadkit .
      - name: Run the Docker image
        run: |
          docker run --rm tadkit python main.py
